feat: reference hide actions prop
contentful/field-editors pull request #1120
Opened 2022-04-26 13:18 UTC by YvesRijckaert

Add a prop `hideActions` to `MultipleEntryReferenceEditor` to be able to hide the actions menu completely.
This is to fix a bug when a user without editing permissions could still open the actions menu in the web app.

2022-04-27 06:25 UTC, denkristoffer commented
Hey @YvesRijckaert, can we avoid adding this complexity? Looking at the code it seems like the menu item shouldn't be rendered if `onRemove` is not passed to the editor, would that acheive the same result as this new flag?

2022-04-27 08:35 UTC, YvesRijckaert commented
@denkristoffer I made the changes that we discussed. Removed the general `hasActions` prop and exposed these two props instead: `hasRemoveActions` and `hasMoveActions`

2022-04-27 11:12 UTC, denkristoffer requested changes
Looks good but I think we should align the naming.

2022-04-27 11:12 UTC, denkristoffer commented on packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
> +    const { hasCardEditActions, hasMoveActions, hasRemoveActions } = props;
I think we should stick to the `hasCard...Actions` naming for all of them here.

2022-04-28 07:49 UTC, denkristoffer approved these changes
Thank you 🙇

2022-04-28 07:55 UTC, merged