fix: use available CTs instead of only readable
contentful/field-editors pull request #1562
Opened 2023-12-15 14:18 UTC by SofiaMargariti

2023-12-18 14:14 UTC, Chaoste approved these changes
Nice fix. If you have time for this, I would appreciate a small comment next to the code, so we don't break this later again

2023-12-19 11:46 UTC, z0al requested changes
Sorry to block but just want to make sure I understand this. it seems `readableContentTypes` are only ever used in the places you changed in this PR, so does that mean we should remove them from the reference editor props?

Also, any reason why not to fix this on the app level?

2023-12-19 12:06 UTC, SofiaMargariti commented
> Sorry to block but just want to make sure I understand this. it seems `readableContentTypes` are only ever used in the places you changed in this PR, so does that mean we should remove them from the reference editor props?
>

Good point, I didn't notice they are not used anymore, we could remove them in this case.

> Also, any reason why not to fix this on the app level?
Do you mean the web app here? This logic is all encapsulated inside the field-editor itself, it essentially determines the CTs to show based on field validations and permissions, they cannot be overridden from the outside atm and introducing new parameters seemed that it would complicate the logic even more. Do you have another suggestion?

2023-12-19 12:54 UTC, z0al commented
> Do you mean the web app here? This logic is all encapsulated inside the field-editor itself

You're right @SofiaMargariti , I was under the impression that the list is passed down from the host app but I was wrong. In that case, let's remove please the `readableContentTypes` related logic and 🚢

2023-12-19 12:55 UTC, z0al approved these changes

2023-12-19 12:55 UTC, z0al approved these changes

2023-12-19 12:55 UTC, z0al approved these changes

2023-12-20 07:27 UTC, merged