feat: 🎸 do not show link actions on full reference/media fields
contentful/field-editors pull request #437
Opened 2020-10-07 16:57 UTC by DanweDE

We do not want to show the link actions on a reference or media field which is already full. This is true for both the current editor link design as well as the experimental CombinedLinkActions design.

2020-10-08 08:50 UTC, suevalov requested changes
Hmm, I'm not sure if simply hiding them is a good solution actually. Could we maybe change isDisabled property if we hit the limit and wrap the button with `Tooltip` component that explains why it is disabled?

I'm afraid that people might start asking "Where is my buttons?" and there will be support tickets if we simply hide them.

Could we discuss this change with Design and maybe PM?

2020-10-08 10:23 UTC, DanweDE commented
> I'm afraid that people might start asking "Where is my buttons?" and there will be support tickets if we simply hide them.

I would say we should follow the design patterns we have in disabled vs. hidden questions (I hope we have guiding principles here) and try out hidden buttons first if that's what we would usually do in such cases.

> Could we discuss this change with Design and maybe PM?

The change is coming form design (cc @joaoramos could you please verify that we want to hide the button, or would you prefer changing these to disabled buttons with a tooltip in this case?) 

> Hmm, I'm not sure if simply hiding them is a good solution actually. Could we maybe change isDisabled property if we hit the limit and wrap the button with Tooltip component that explains why it is disabled?

If we want to change this we'll need some design for this new disabled/tooltipped state in case of both the new and old design of these buttons in the new app (e.g. I imagine we wouldn't want them to take this much space in that case and hide the placeholder). Ideally by tomorrow as I am out today and next week, otherwise I'll have to stale this for a week or hand over to another dev.

Reminder new design:
![style-update](https://user-images.githubusercontent.com/101926/95445606-7d14f280-095f-11eb-9a13-01878ff5e32b.png)

Reminder old design:
![link-buttons-old-design](https://user-images.githubusercontent.com/101926/95446254-560af080-0960-11eb-9519-d4e7313f737c.png)

2020-10-08 10:33 UTC, joaoramos commented
Those are valid concerns, @suevalov. If removing the buttons raises concerns with customers, we'll address that and course correct. Having disabled states and further UI to address these situations will potentially raise cognitive load which, unfortunately, is rather high already. Plus, they can still use the options menu to add references, where they will get a disabled action for it. I'd move forward with the PR.

2020-10-09 09:53 UTC, suevalov approved these changes

2020-10-09 09:54 UTC, merged