feat: add contentful editor provider and remove editor key
contentful/field-editors pull request #828
Opened 2021-09-02 10:48 UTC by cezarsmpio

The `key` property breaks the editor regardless of its value.

2021-09-02 13:31 UTC, cezarsmpio commented on packages/rich-text/src/RichTextEditor.tsx
> +                  key={`rich-text-editor-${externalReset}`}
We still need `key` for the collaborative editing.

2021-09-02 15:03 UTC, DanweDE requested changes
This bug still seems an issue with this change:

![issue-back](https://user-images.githubusercontent.com/101926/131867969-1e4230d9-9653-4021-aa5a-3754fd0a579b.gif)

It only happens in the 2nd instance, not in the 1st instance.

2021-09-02 16:13 UTC, cezarsmpio commented
@DanweDE did a few more tests and it seems to be working fine, even on different locales with multiple RTE fields:

![image](https://user-images.githubusercontent.com/954889/131879688-b1d5191c-6eed-4484-9f3a-5403fb3de0f4.png)

![image](https://user-images.githubusercontent.com/954889/131879673-60d859df-94a2-4089-9e03-db9b0d4f9940.png)

2021-09-03 06:52 UTC, DanweDE approved these changes

2021-09-03 07:04 UTC, merged